-- BREAKLINE COMMUNITY SCHEMA
-- Real data only: no seeded members, likes, LFGs, or reputation.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  operator_name text not null unique,
  avatar_url text,
  bio text default '',
  reputation integer not null default 0,
  is_founding_operator boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.lfg_posts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  game text not null,
  title text not null,
  party_size text not null default '1/3',
  region text not null default 'NA',
  status text not null default 'open' check (status in ('open','closed')),
  created_at timestamptz not null default now()
);

create table if not exists public.build_likes (
  build_id bigint not null references public.builds(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (build_id, user_id)
);

alter table public.profiles enable row level security;
alter table public.lfg_posts enable row level security;
alter table public.build_likes enable row level security;

create policy "Profiles are public" on public.profiles for select using (true);
create policy "Users create their profile" on public.profiles for insert with check (auth.uid() = id);
create policy "Users update their profile" on public.profiles for update using (auth.uid() = id);

create policy "Open LFG posts are public" on public.lfg_posts for select using (status = 'open' or auth.uid() = user_id);
create policy "Users create LFG posts" on public.lfg_posts for insert with check (auth.uid() = user_id);
create policy "Users update their LFG posts" on public.lfg_posts for update using (auth.uid() = user_id);
create policy "Users delete their LFG posts" on public.lfg_posts for delete using (auth.uid() = user_id);

create policy "Likes are public" on public.build_likes for select using (true);
create policy "Users like builds once" on public.build_likes for insert with check (auth.uid() = user_id);
create policy "Users remove their likes" on public.build_likes for delete using (auth.uid() = user_id);

create or replace function public.handle_new_operator()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, operator_name, is_founding_operator)
  values (
    new.id,
    coalesce(nullif(new.raw_user_meta_data->>'operator_name',''), split_part(new.email,'@',1)),
    (select count(*) from public.profiles) < 100
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_operator();

create or replace function public.increment_reputation(target_user uuid, amount integer)
returns void
language sql
security definer set search_path = public
as $$
  update public.profiles set reputation = greatest(0, reputation + amount) where id = target_user;
$$;
