const cfg = window.BREAKLINE_CONFIG || {};
const client = cfg.supabaseUrl && cfg.supabaseAnonKey ? window.supabase.createClient(cfg.supabaseUrl, cfg.supabaseAnonKey) : null;
const starter = [
  {title:'The Quiet Operator',type:'ASSAULT RIFLE',weapon:'M4A1 · Full stealth / mid-range',price:184500,author:'GHOSTRIDER',likes:24,style:'weapon-one',tag:'TOP PICK',silhouette:'ar'},
  {title:'Zero to Hero',type:'SMG',weapon:'MP5 · Close quarters / cheap',price:42300,author:'RAZE',likes:18,style:'weapon-two',tag:'BUDGET KING',tagClass:'budget',silhouette:'smg'},
  {title:'Valley Watcher',type:'DMR',weapon:'M110 · Long range / precision',price:216750,author:'SUNDOWN',likes:11,style:'weapon-three',tag:'META',tagClass:'meta',silhouette:'dmr'}
];
let builds = JSON.parse(localStorage.getItem('breakline-builds') || 'null') || starter;
let operator = JSON.parse(localStorage.getItem('breakline-operator') || 'null'), filter = 'ALL', query = '';
const grid = document.querySelector('#build-grid'), toast = document.querySelector('#toast');
const notify = m => { toast.textContent=m; toast.classList.add('show'); setTimeout(()=>toast.classList.remove('show'),2800); };
const safe = v => { const x=document.createElement('span'); x.textContent=v||''; return x.innerHTML; };
function card(b,i){const tone=b.style||['weapon-one','weapon-two','weapon-three'][i%3],tag=b.tag||(b.type==='BUDGET'?'BUDGET':'COMMUNITY');return `<article class="build-card"><div class="card-visual ${tone}"><span class="tier">COMMUNITY</span><button class="save" data-save="${i}" aria-label="Save build">♡</button><div class="weapon-silhouette ${b.silhouette||'ar'}"></div><span class="tag ${b.tagClass||''}">${tag}</span></div><div class="card-body"><div class="card-meta"><span>${b.type}</span><span class="up">▲ ${b.likes||0}</span></div><h3>${safe(b.title)}</h3><p>${safe(b.weapon)}</p><div class="card-foot"><span class="price">₭ ${Number(b.price).toLocaleString()}</span><span class="author">BY <b>${safe(b.author)}</b></span></div></div></article>`}
function render(){const shown=builds.filter(b=>(filter==='ALL'||b.type===filter||(filter==='BUDGET'&&Number(b.price)<60000))&&`${b.title} ${b.weapon} ${b.type}`.toLowerCase().includes(query));grid.innerHTML=shown.length?shown.map(card).join(''):'<p class="empty-state">NO BUILDS MATCH THIS INTEL.</p>';document.querySelector('#build-count').textContent=builds.length}
function updateUser(){if(operator)document.querySelector('.login').textContent=operator.name.toUpperCase()}
async function loadCommunity(){if(!client)return;const {data,error}=await client.from('builds').select('*').order('created_at',{ascending:false});if(error){notify('COMMUNITY DATABASE COULD NOT LOAD.');return}builds=data.map(b=>({...b}));render();const {data:{user}}=await client.auth.getUser();if(user){operator={id:user.id,name:user.user_metadata.display_name||user.email.split('@')[0],email:user.email};updateUser()}}
document.querySelectorAll('[data-open-auth]').forEach(x=>x.addEventListener('click',()=>document.querySelector('#auth-modal').showModal()));
document.querySelectorAll('[data-open-submit]').forEach(x=>x.addEventListener('click',()=>{if(!operator){notify('CREATE A PROFILE BEFORE POSTING.');document.querySelector('#auth-modal').showModal()}else document.querySelector('#submit-modal').showModal()}));
document.querySelectorAll('[data-close]').forEach(x=>x.addEventListener('click',()=>x.closest('dialog').close()));
document.querySelectorAll('.filter').forEach(x=>x.addEventListener('click',()=>{document.querySelector('.filter.selected').classList.remove('selected');x.classList.add('selected');filter=x.dataset.filter;render()}));
document.querySelector('#build-search').addEventListener('input',e=>{query=e.target.value.toLowerCase();render()});
grid.addEventListener('click',e=>{if(e.target.dataset.save===undefined)return;const n=Number(e.target.dataset.save),saved=JSON.parse(localStorage.getItem('breakline-saved')||'[]'),has=saved.includes(n);localStorage.setItem('breakline-saved',JSON.stringify(has?saved.filter(x=>x!==n):[...saved,n]));e.target.textContent=has?'♡':'♥';notify(has?'REMOVED FROM SAVED BUILDS.':'BUILD SAVED.')});
document.querySelector('#auth-form').addEventListener('submit',async e=>{e.preventDefault();const name=document.querySelector('#auth-name').value.trim(),email=document.querySelector('#auth-email').value.trim(),password=document.querySelector('#auth-password').value;if(client){const {data,error}=await client.auth.signUp({email,password,options:{data:{display_name:name}}});if(error){notify(error.message.toUpperCase());return}operator={id:data.user?.id,name,email};notify(data.session?'PROFILE CREATED.':'CHECK YOUR EMAIL TO CONFIRM YOUR PROFILE.')}else{operator={name,email};localStorage.setItem('breakline-operator',JSON.stringify(operator));notify('PROFILE CREATED IN DEMO MODE.')}document.querySelector('#auth-modal').close();updateUser()});
document.querySelector('#build-form').addEventListener('submit',async e=>{e.preventDefault();if(!operator)return;const b={title:document.querySelector('#build-title').value.trim(),type:document.querySelector('#build-type').value,weapon:document.querySelector('#build-weapon').value.trim(),price:Number(document.querySelector('#build-price').value),notes:document.querySelector('#build-notes').value.trim(),author:operator.name,likes:0};if(client){const {error}=await client.from('builds').insert({...b,user_id:operator.id});if(error){notify(error.message.toUpperCase());return}}else{builds.unshift(b);localStorage.setItem('breakline-builds',JSON.stringify(builds))}document.querySelector('#build-form').reset();document.querySelector('#submit-modal').close();filter='ALL';document.querySelector('.filter.selected').classList.remove('selected');document.querySelector('[data-filter="ALL"]').classList.add('selected');if(client)await loadCommunity();else render();document.querySelector('#builds').scrollIntoView({behavior:'smooth'});notify(client?'BUILD PUBLISHED.':'BUILD PUBLISHED IN DEMO MODE.')});
render();updateUser();loadCommunity();
